# permissions to do viewer telegrammessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegrammessage-viewer-role
rules:
- apiGroups:
  - just.learning.io.just.learning.io
  resources:
  - telegrammessages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - just.learning.io.just.learning.io
  resources:
  - telegrammessages/status
  verbs:
  - get
