# permissions to do edit telegrammessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegrammessage-editor-role
rules:
- apiGroups:
  - just.learning.io.just.learning.io
  resources:
  - telegrammessages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - just.learning.io.just.learning.io
  resources:
  - telegrammessages/status
  verbs:
  - get
  - patch
  - update
