apiVersion: just.learning.io.just.learning.io/v1beta1
kind: TelegramMessage
metadata:
  generation: 1
  labels:
    controller-tools.k8s.io: "1.0"
  name: test
  namespace: default
spec:
  messagetodeliver: "Hello, Coder!"
  token: "<your-bot-token>"
  chatid: "<your-chat-id>"
status: {}
